name: PINGO
markdown: redcarpet
pygments: false
baseurl: http://www.trypingo.com/
include: [".htaccess"]
exclude: ["scss", "node_modules", "bower_components", "package.json", "gruntfile.js", "README.md"]
